{% set name = "python-cudnn-frontend" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cudnn-frontend/archive/v{{ version }}.tar.gz
  sha256: 22e9475b4e3c1a87ce81548d13019719fa55257575866724a35fede6de827c8b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - CUDNN_FRONTEND_LOG_INFO=1
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  number: 0
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib("c") }}
    - cmake >=3.17
    - make
    - ninja
  host:
    - cudnn
    - pip
    - pybind11
    - python
    - setuptools >=64
  run:
    - python

test:
  imports:
    - cudnn
  commands:
    - pip check
    - python -c "import cudnn; assert cudnn.backend_version() >= 8907"
    # See if C++ header files are included
    - ls -lh $PREFIX/lib/python$PY_VER/site-packages/include/*
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/cudnn-frontend
  summary: cuDNN FrontEnd API
  license: MIT
  license_file:
    - LICENSE.txt
    - include/cudnn_frontend/thirdparty/nlohmann/LICENSE.MIT

extra:
  recipe-maintainers:
    - weiji14
