schema_version: 1

context:
  name: python-cudnn-frontend
  version: "1.14.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/cudnn-frontend/archive/v${{ version }}.tar.gz
  sha256: 29de176ec46ed4bdf1d2204d28016233fb009a0c64e83e07e9aabc2fb32be5d8

build:
  number: 2
  string: cuda${{ cuda_compiler_version | replace('.', '') }}py${{ CONDA_PY }}h${{ PKG_HASH }}_${{ PKG_BUILDNUM }}
  skip: cuda_compiler_version in (undefined, "None") or (not linux)
  script:
    env:
      CUDNN_FRONTEND_LOG_INFO: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - ${{ stdlib("c") }}
    - cmake >=3.18
    - make
    - ninja
  host:
    - cudnn
    - pip
    - pybind11
    - python
    - setuptools >=64
  run:
    - python

tests:
  - python:
      imports:
        - cudnn
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - python -c "import cudnn; assert cudnn.backend_version() >= 90300"

      # PY_VER is not available in 'tests' section with rattler-build
      - export PY_VER=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
      - ls -lh $PREFIX/lib/python$PY_VER/site-packages/include/*
      - test -f $PREFIX/lib/python$PY_VER/site-packages/include/cudnn_frontend.h

about:
  summary: cuDNN FrontEnd API
  license: MIT
  license_file:
    - LICENSE.txt
    - include/cudnn_frontend/thirdparty/nlohmann/LICENSE.MIT
  homepage: https://github.com/NVIDIA/cudnn-frontend

extra:
  recipe-maintainers:
    - weiji14
